# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('project-example', ['project','network', 'internet', 'mobility','aodv','olsr', 'dsdv','dsr','applications','netanim','wifi', 'propagation', 'wave','flow-monitor', 'config-store'])
    obj.source = 'project-example.cc'