# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('project', ['core'])
    module.source = [
        'model/TRIPApplication.cc',
        'model/project-group.cc',
        'model/project-bsm-application.cc',
        'model/AggregateApplication.cc',
        'model/VanetApplication.cc',
        'model/RoadEvents.cc',
        'model/EventLogger.cc',
        'helper/VanetApplicationHeper.cc',
        'helper/project-bsm-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('project')
    module_test.source = [
        'test/project-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/project-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'project'
    headers.source = [
        'model/TRIPApplication.h',
        'model/project-group.h',
        'model/project-bsm-application.h',
        'model/AggregateApplication.h',
        'model/VanetApplication.h',
        'model/RoadEvents.h',
        'model/EventLogger.h',
        'helper/VanetApplicationHeper.h',
        'helper/project-bsm-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

